<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pscm</string>
	</array>
	<key>name</key>
	<string>p-scheme</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\!\@</string>
			<key>comment</key>
			<string>Block comment</string>
			<key>end</key>
			<string>\#\$</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>begin</string>
			<key>match</key>
			<string>\b(Ready to Go)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fun-to-var</string>
			<key>match</key>
			<string>([\/])([\/])</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>next_line</string>
			<key>match</key>
			<string>([&lt;])([\~])</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>arith ops</string>
			<key>match</key>
			<string>[\+]|[\-]|[\*]|[\/]|[\%]|[\^]|[\!]|(v)([\/])</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>bool ops</string>
			<key>match</key>
			<string>\b(and|or|xor|nand|nor|not)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comparison ops</string>
			<key>match</key>
			<string>[&lt;]|[&gt;]|[\=]</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>other primitives</string>
			<key>match</key>
			<string>\b(print|write|input|val|if|ifTrue|ifFalse|empty|while|for|in|claim|done|exit)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>"([^\\"]|\\.)*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>integer</string>
			<key>match</key>
			<string>\b(([\.])([0-9])|[0-9]|([0-9])([\.])([0-9]))+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.bool</string>
			<key>match</key>
			<string>\b(true|false|maybe|Nothing)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>types</string>
			<key>match</key>
			<string>\b(num|bool|nonetype|str|list|define)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>checks</string>
			<key>match</key>
			<string>\b(check-expect|check-error)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>func_name</string>
			<key>match</key>
			<string>\w+(?= +define\b)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>vars</string>
			<key>match</key>
			<string>\b(it|today)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pscm</string>
	<key>uuid</key>
	<string>fa220c5d-0ad5-4a52-8027-37e13443b1fc</string>
</dict>
</plist>

